pipeline {
    agent {
     label 'akshay'
  }
    stage('build') {
      steps {
    // One or more steps need to be included within the steps block.
  }

    post {
     success {
      // One or more steps need to be included within each condition's block.
    }
  }
}
        stage("test"){
            steps{
                echo "this is testing stage"
                // sh "mvn clean package"
            }
        }
    }
}
          
